### ISSUE TITLE
can u please add onClick event code in the sample

### ISSUE THREAD

**Issue by kprathap23** [LeeReindeer/Tree2View#1]

**Comment by LeeReindeer** [comment]
Hi, There is a default click event of treeview at [here](https://github.com/LeeReindeer/Tree2View/blob/master/treeview/src/main/java/xyz/leezoom/view/treeview/TreeView.java#L346), if you want to write a custom click listener, you'd better refer to it.

**Comment by kprathap23** [comment]
Thank you very much..
