### ISSUE TITLE
enable horizontal scroll if the treeview is too many multi levels

### ISSUE THREAD

**Issue by kprathap23** [LeeReindeer/Tree2View#2]
![screenshot-1522405187210](https://user-images.githubusercontent.com/2254065/38134876-b321eba8-3432-11e8-8102-fb5b0217f14f.jpg)

Can you please take a look at this issue if possible for you..
If you see in the screen shot, if there are too many levels the data aligns to right with two lines and the last element even does not show..

**Comment by LeeReindeer** [comment]
@kprathap23 It's a known problem.This treeview use padding to show items like a "tree", so if you have too many levels of children, the padding won't work well.

- Use horizontal scroll that will require plenty of customization, but doable.
- Did you try adding `HorizontalScrollView`  as the parent of `TreeView`?
- An alternative to showing more children is to reduce the indent in your adapter: `setPadding(holder.tv, depth, 10);`(the third param)
